### ISSUE TITLE
Jsonfile read error

### ISSUE THREAD

**Issue by LucaswasTaken** [cereja-project/cereja#127]
![image](https://user-images.githubusercontent.com/21283326/112770348-c71c8e00-8ffc-11eb-86c7-4609e6962789.png)

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by jlsneto** [comment]
JsonFile implements has been removed on #125
* Available only <=1.3.3 versions.
* Use `cereja.file.FileIO.load(path)` or directly `cereja.file.FileIO.json(path)`
